name: 'Leo Hermanto '
favicon: null
layout_spectrum: 0.73451
typography_spectrum: 0.69669
title: 'The Perspective & Journey of Life'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050402'
    - '#ad0b02'
    - '#d7a37c'
    - '#aa7845'
    - '#614c47'
  brandStrength: 0.625
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
