name: 'Leo Hermanto '
favicon: null
layout_spectrum: 1
typography_spectrum: 0.46439426532015204
title: 'The Perspective & Journey of Life'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#12151c'
    - '#706f6b'
    - '#a01d35'
    - '#e27091'
  brandStrength: 0.5
  lightness: 0.032243824331089854
  saturation: 0.3473576621618122
  rhythmicContrast: 0.7487387852743268
purpose: []
